ActivityManager/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActivityManager.Models
{
    public class Team
    {
        /*//pentru relatia many-to-many
        public Team()
        {
            ApplicationUser = new HashSet<ApplicationUser>();
        }*/

        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "The Name field is required.")]
        public string Name { get; set; }
        public string OrganizerId { get; set; }

        /*public int ProjectId { get; set; }
        public virtual Project Project { get; set; }*/

        public virtual ApplicationUser Organzier { get; set; }

        //Pentru many-to-many
        public virtual ICollection<UserTeam> UserTeams { get; set; }

        // Se aduaga acest atribute pentru a putea prelua toate proiectele si statusurile
        public IEnumerable<Task> Tasks { get; set; }
        public IEnumerable<Project> Projects { get; set; }
        //public virtual ICollection<ApplicationUser> ApplicationUser { get; set; }
    }
}

ActivityManager/Controllers/TaskController.cs
using ActivityManager.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ActivityManager.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpGet]
        public ActionResult GetAll()
        {
            var tasks = db.Tasks;
            ViewBag.Tasks = tasks;
            return View();
        }

        public ActionResult Show(int id)
        {
            bool isMember = false;
            bool isOrganizer = false;

            Task task = db.Tasks.Include(i => i.TaskStatus).Include(i => i.CreatedBy).Include(i => i.AssignedTo)
                .SingleOrDefault(x => x.Id == id);
            
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if ( isMember || isOrganizer || User.IsInRole("Administrator"))
            {
                if (TempData.ContainsKey("message"))
                {
                    ViewBag.message = TempData["message"].ToString();
                }
                task.Comments = db.Comments.Where(x => x.TaskId == id).Include(x => x.User);
                ViewBag.Task = task;
                ViewBag.afisareButoane = false;
                if (isOrganizer || User.IsInRole("Administrator"))
                {
                    ViewBag.afisareButoane = true;
                }
                ViewBag.esteAdmin = User.IsInRole("Administrator");
                ViewBag.utilizatorCurent = User.Identity.GetUserId();
                return View(task);
            }
            else
            {
                TempData["message"] = "You don't have the right to see this task!";
                return Redirect("~");
            }
        }

        public ActionResult New(int? projectId)
        {
            if (projectId != null)
            {
                Task task = new Task
                {
                    Projects = GetAllProjects() //vor trebui aduse doar proiectele echipei din care este membru
                };

                bool isMember = false;
                bool isOrganizer = false;
                GetRoleInTeam(ref isMember, ref isOrganizer, projectId ?? 0);

                if (isOrganizer || User.IsInRole("Administrator"))
                {
                        task.ProjectId = projectId.Value;
                        return View(task);
                }
                else
                {
                        TempData["message"] = "You don't have the right to create a new task!";
                        return Redirect("~");
                }
            }
            TempData["message"] = "You need to select a project first!";
            return Redirect("~");
        }

        [HttpPost]
        public ActionResult New(Task task)
        {
            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if (isOrganizer || User.IsInRole("Administrator"))
            {
                task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                try
                {
                    if (ModelState.IsValid)
                    {
                        task.CreatedOn = DateTime.Now;
                        task.StartDate = null;
                        task.EndDate = null;
                        task.TaskStatusId = 1;
                        task.CreatedById = User.Identity.GetUserId();
                        task.AssignedToId = null;
                        //task.TaskStatuses = GetAllTaskStatuses();
                        db.Tasks.Add(task);
                        db.SaveChanges();
                        TempData["message"] = "The task has been created!";
                        return RedirectToAction("Show", "Project", new { id = task.ProjectId });
                    }
                    else
                    {
                        return View(task);
                    }
                }
                catch (Exception e)
                {
                    System.Console.WriteLine(e);
                    return View(task);
                }
            }
            else
            {
                TempData["message"] = "You don't have the right to create a new task!";
                return Redirect("~");
            }
        }

        public ActionResult Edit(int id)
        {
            Task task = db.Tasks.Where(x => x.Id == id).Include(x => x.Project).FirstOrDefault();

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if (isOrganizer|| isMember || User.IsInRole("Administrator"))
            {
                task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                task.TaskStatuses = GetAllTaskStatuses();
                task.TeamPersons = GetTeamPersons(task.Project.TeamId);
                task.Comments = db.Comments.Where(x => x.TaskId == id);
                ViewBag.Task = task;
                // daca este doar membru, poate modifica doar statusul
                ViewBag.SeeAll = (isOrganizer || User.IsInRole("Administrator"));
                return View(task);
            }
            else
            {
                TempData["message"] = "You don't have the right to edit this task!";
                return Redirect("~");
            }
        }

        [HttpPut]
        public ActionResult Edit(int id, Task requestTask)
        {
            Task task = db.Tasks.Where(x => x.Id == id).Include(x => x.Project).FirstOrDefault();
            requestTask.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
            requestTask.TaskStatuses = GetAllTaskStatuses();
            requestTask.TeamPersons = GetTeamPersons(task.Project.TeamId);

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);
            ViewBag.SeeAll = (isOrganizer || User.IsInRole("Administrator"));

            try
            {
                if (ModelState.IsValid)
                {
                    task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                    task.TaskStatuses = GetAllTaskStatuses();
                    task.TeamPersons = GetTeamPersons(task.Project.TeamId);
                    if (requestTask.StartDate > requestTask.EndDate)
                    {
                        TempData["error"] = "The start date cannot be set after the end date.";
                        //                        ViewBag.message = TempData["error"].ToString();
                        return View(requestTask);
                    }
                    //if ((requestTask.TaskStatusId == 1 && (requestTask.StartDate != null || requestTask.EndDate != null))
                    //    || (requestTask.TaskStatusId == 2 && (requestTask.StartDate == null || requestTask.EndDate != null))
                    //    || (requestTask.TaskStatusId == 3 && (requestTask.StartDate == null || requestTask.EndDate == null)))
                    //{
                    //    TempData["message"] = "Datele introduse nu sunt corecte!";
                    //    return View(requestTask);
                    //}
                    task.Comments = db.Comments.Where(x => x.TaskId == id);
                    if (TryUpdateModel(task))
                    {
                        task.Title = requestTask.Title;
                        task.Description = requestTask.Description;
                        task.StartDate = requestTask.StartDate;
                        task.EndDate = requestTask.EndDate;
                        task.TaskStatusId = requestTask.TaskStatusId;
                        task.AssignedToId = requestTask.AssignedToId;
                        db.SaveChanges();
                        TempData["message"] = "The task has been edited!";
                    }
                    return RedirectToAction("Show", new { id = task.Id });
                }
                else
                {
                    return View(requestTask);
                }

            }
            catch (Exception e)
            {
                return View(requestTask);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            Task task = db.Tasks.Find(id);

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if ((task.CreatedById == User.Identity.GetUserId() && isOrganizer )|| User.IsInRole("Administrator"))
            {
                db.Tasks.Remove(task);
                db.SaveChanges();
                TempData["message"] = "The task was deleted!";
                return RedirectToAction("Show", "Project", new { id = task.ProjectId });
            }
            else
            {
                TempData["message"] = "You don't have the right to delete this task!";
                return Redirect("~");
            }
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllProjects()
        {
            var selectList = new List<SelectListItem>();
            string userId = User.Identity.GetUserId();
            var teamsIds = db.UserTeams.Where(x => x.UserId == userId).Select(x => x.TeamId);
            var projects = db.Projects.Where(x => teamsIds.Contains(x.TeamId));
            foreach (var project in projects)
            {
                selectList.Add(new SelectListItem
                {
                    Value = project.Id.ToString(),
                    Text = project.Name
                });

ActivityManager/Controllers/UserTeamController.cs
using ActivityManager.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActivityManager.Controllers
{
    [Authorize]
    public class UserTeamController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }


        public ActionResult New(int teamId)
        {
            Team team = db.Teams.Find(teamId);
            if ((team.OrganizerId == User.Identity.GetUserId() && User.IsInRole("Organizer")) || User.IsInRole("Administrator"))
            {
                UserTeam userTeam = new UserTeam
                {
                    AllUsers = GetAllUsers(teamId),
                    TeamId = teamId
                };
                return View(userTeam);
            }
            else
            {
                TempData["message"] = "You don't have the right to create a project!";
                return Redirect("~"); ;
            }

        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> New(UserTeam userTeam)
        {
            userTeam.AllUsers = GetAllUsers(userTeam.TeamId);
            try
            {
                if (ModelState.IsValid)
                {
                    db.UserTeams.Add(userTeam);
                    db.SaveChanges();

                    // Adaugam rolul de membru
                    ApplicationDbContext context = new ApplicationDbContext();
                    var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
                    var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                    if (!UserManager.IsInRole(userTeam.UserId,"Member"))
                    {
                        UserManager.AddToRole(userTeam.UserId, "Member");
                        db.SaveChanges();
                    }

                    return RedirectToAction("Show", "Team", new { id = userTeam.TeamId });
                }
                else
                {
                    return View(userTeam);
                }
            }
            catch (Exception e)
            {

                return View(userTeam);
            }
        }

        [HttpDelete]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int teamId, string userId)
        {
            UserTeam userTeam = db.UserTeams.Where(x => x.UserId == userId && x.TeamId == teamId).FirstOrDefault();
            db.UserTeams.Remove(userTeam);
            db.SaveChanges();
            TempData["message"] = "User has been succesfully removed form this team";

            //Stergem rolul de membru 
            ApplicationDbContext context = new ApplicationDbContext();
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            List<UserTeam> otherUserTeams = db.UserTeams.Where(x => x.UserId == userId).ToList();
            if (otherUserTeams.Count() == 0)
            {
                UserManager.RemoveFromRole(userId, "Member");

                db.SaveChanges();
            }
            else
            {
                //Verificam daca nu cumva e numai organizator
                bool removeMember = true;
                foreach (var uT in otherUserTeams)
                {
                    Team team = db.Teams.Where(x => x.Id == uT.TeamId).First();
                    if (team.OrganizerId != userId)
                    {
                        removeMember = false;
                        break;
                    }
                }
                if (removeMember)
                {
                    UserManager.RemoveFromRole(userId, "Member");
                }

            }
            return RedirectToAction("Show", "Team", new { id = userTeam.TeamId });
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllUsers(int teamId)
        {
            var selectList = new List<SelectListItem>();
            var users = db.Users;
            Team team = db.Teams.Where(u => u.Id == teamId).FirstOrDefault();
            var userIds = team.UserTeams.Select(x => x.UserId);
            foreach (var user in users)
            {
                if(!userIds.Contains(user.Id))
                {
                    selectList.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Email
                    });
                }             
            }
            return selectList;
        }
    }
}

ActivityManager/Views/Team/Edit.cshtml
@model ActivityManager.Models.Team

@{
    ViewBag.Title = "Edit";
}

<h2>@ViewBag.Title</h2>
<form method="post" action="/Team/Edit/@Model.Id">
    @Html.HttpMethodOverride(HttpVerbs.Put)
    @Html.HiddenFor(m => m.Id)
    <div class="panel panel-default">
        <div class="panel-body">
            <strong> @Html.Label("Name", "Name") </strong>
            <br />
            @Html.TextBox("Name", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger " })
        </div>
        <div class="panel-footer">
            <button class="btn btn-sm btn-success" type="submit">Save</button>
            <a class="btn btn-sm btn-danger" href="/Team/Show/@Model.Id">Cancel</a>
        </div>
    </div>
</form>

ActivityManager/Views/Team/Index.cshtml
@{
    ViewBag.Title = "Teams";
}

<h1>
    @ViewBag.Title
    <a href="@Url.Action("New", "Team")" class="btn btn-success" role="button" style="float: right;"> Add new team</a>
</h1>


@foreach (var team in ViewBag.Teams)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <form method="post" action="/Team/Delete/@team.Id">
                <a class="btn btn-sm btn-success" href="/Team/Show/@team.Id">Team Details</a>
                @if (@team.OrganizerId == ViewBag.UserId || ViewBag.isAdmin)
                {
                    @Html.HttpMethodOverride(HttpVerbs.Delete)
                    <button class="btn btn-sm btn-danger" type="submit"> Delete </button>
                }

            </form>
        </div>
        <div class="panel-body">
            <h2>@team.Name</h2>
        </div>
        <div class="panel-footer">
            <h4>
                <strong>
                    Members
                </strong>
            </h4>
            <br />
            <ul class="list-group">
                @foreach (var userTeam in team.UserTeams)
                {
                    <li class="list-group-item">
                        @userTeam.User.Email
                        @if (userTeam.User.Id == team.OrganizerId)
                        {
                            <strong><em> - Organizer </em></strong>
                        }
                    </li>
                }
            </ul>
        </div>
    </div>
}

ActivityManager/Views/Team/New.cshtml
@model ActivityManager.Models.Team

@{
    ViewBag.Title = "New team";
}

<h2>@ViewBag.Title</h2>



<div class="panel panel-default">
    <form method="post" action="/Team/New">
        <div class="panel-body">
            @Html.Label("Name", "Name")
            <br />
            @Html.TextBox("Name", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger " })
            <br />
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-sm btn-success"> Add </button>
            <a class="btn btn-sm btn-danger" href="">Cancel</a>
        </div>
    </form>
</div>

ActivityManager/Views/Team/Show.cshtml
@model ActivityManager.Models.Team

@{
    ViewBag.Title = "Team " + @Model.Name;
}

<h2>@ViewBag.Title</h2>

@if (ViewBag.message != null)
{
    <br />
    <div class="alert alert-success" role="alert">
        <h4>@ViewBag.message</h4>
    </div>
}

<div class="panel panel-default">
    <div class="panel-heading">
        <a href="/Team/Index" class="btn btn-sm btn-success" role="button"> Back to teams</a>
        @if (@ViewBag.isOrganizerOrAdministrator)
        {
            <a class="btn btn-sm btn-success" href="/Team/Edit/@Model.Id">Edit team</a>
            <a href="@Url.Action("New", "Project", new { teamId = @Model.Id })" class="btn btn-sm btn-success" role="button"> Add new project</a>
            <a href="@Url.Action("New", "UserTeam", new { teamId = @Model.Id })" class="btn btn-sm btn-success" role="button"> Add a new member </a>
        }
    </div>


    <div class="panel-footer">
        <h3>Projects</h3>
        @foreach (var project in Model.Projects)
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    @project.Name
                </div>
                <div class="panel-body">
                    @project.Description
                </div>
                <div class="panel-footer">
                    <form method="post" action="/Project/Delete/@project.Id">
                        <a href="@Url.Action("Show", "Project", new { id = project.Id })" class="btn btn-sm btn-success" role="button"> View</a>
                        @if (@ViewBag.isOrganizerOrAdministrator)
                        {
                            @Html.HttpMethodOverride(HttpVerbs.Delete)
                            <button class="btn btn-sm btn-danger" type="submit"> Delete </button>
                        }
                    </form>
                </div>
            </div>
        }


        <h3>Tasks</h3>
        @foreach (var task in Model.Tasks)
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    @task.Title
                </div>
                <div class="panel-body">
                    <strong>Project: </strong> @task.Project.Name
                    <br />
                    <strong>Description: </strong> @task.Description
                    <br />
                </div>
                <div class="panel-footer">
                    <a href="@Url.Action("Show", "Task", new { id = task.Id })" class="btn btn-sm btn-success" role="button"> View</a>
                </div>
            </div>
        }


        <h3>Members</h3>

            @foreach (var member in Model.UserTeams)
            {
                
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @member.User.Email
                            @if (member.User.Id == Model.OrganizerId)
                            {
                                <strong><em> - Organizer</em></strong>
                            }
                        </div>

                        @if (@ViewBag.isOrganizerOrAdministrator)
                        {
                            <div class="panel-footer">
                                <form method="post" action="/UserTeam/Delete/?userId=@member.UserId&teamId=@member.TeamId">

                                    @Html.HttpMethodOverride(HttpVerbs.Delete)
                                    <button class="btn btn-sm btn-danger" type="submit"> Delete </button>
                                </form>
                            </div>
                        }
                    </div>
                
            }
        
    </div>
</div>