ActivityManager/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActivityManager.Models
{
    public class Task
    {
        [Key]
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int TaskStatusId { get; set; }
        [Required(ErrorMessage = "The Title field is required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "The Description field is required")]
        public string Description { get; set; }
        public string CreatedById { get; set; }
        public string AssignedToId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public virtual Project Project { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual ApplicationUser CreatedBy { get; set; }
        public virtual ApplicationUser AssignedTo { get; set; }


        // Se aduaga acest atribute pentru a putea prelua toate proiectele si statusurile
        public IEnumerable<SelectListItem> Projects { get; set; }
        public IEnumerable<SelectListItem> TaskStatuses { get; set; }
        public IEnumerable<SelectListItem> TeamPersons { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
    }
}

ActivityManager/Controllers/CommentController.cs
using ActivityManager.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActivityManager.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult New (int taskId = -1)
        {
            Comment comment = new Comment();
            if (taskId > -1)
            {
                bool isMember = false;
                bool isOrganizer = false;
                GetRoleInTeam(ref isMember, ref isOrganizer, taskId);

                if (isOrganizer || isMember || User.IsInRole("Administrator"))
                {
                    comment.TaskId = taskId;
                }
                else
                {

                    TempData["message"] = "You don't have the right to add a comment!";
                    return Redirect("~");
                }
            }
            return View(comment);
        }

        [HttpPost]
        public ActionResult New(Comment comment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    comment.CreatedOn = DateTime.Now;
                    comment.UserId = User.Identity.GetUserId();
                    db.Comments.Add(comment);
                    db.SaveChanges();
                    TempData["message"] = "The comment has been created!";
                    return RedirectToAction("Show", "Task", new { id = comment.TaskId });
                }
                else
                {
                    return View(comment);
                }
            }
            catch (Exception e)
            {
                return View(comment);
            }
        }

        public ActionResult Edit(int id)
        {
            Comment comment = db.Comments.Find(id);
            if (comment.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {
                ViewBag.Comment = comment;
                return View(comment);
            }
            else
            {
                TempData["message"] = "You don't have the right to edit this comment!";
                return Redirect("~");
            }
        }

        [HttpPut]
        public ActionResult Edit(int id, Comment requestComment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Comment comment = db.Comments.Find(id);
                    if (TryUpdateModel(comment))
                    {
                        comment.Content = requestComment.Content;
                        db.SaveChanges();
                        TempData["message"] = "The comment has been edited!";
                    }
                    return RedirectToAction("Show", "Task", new { id = comment.TaskId });
                }
                else
                {
                    return View(requestComment);
                }
            }
            catch (Exception e)
            {
                return Redirect("~");
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            Comment comment = db.Comments.Find(id);

            if (comment.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
                TempData["message"] = "The comment has been deleted!";
                return RedirectToAction("Show", "Task", new { id = comment.TaskId });
            }
            else
            {
                TempData["message"] = "You cannot delete this comment!";
                return Redirect("~");
            }

        }

        [NonAction]
        private void GetRoleInTeam(ref bool isMember, ref bool isOrganizer, int taskId)
        {
            string userId = User.Identity.GetUserId();
            Task task = db.Tasks.Find(taskId);
            int teamId = db.Projects.Find(task.ProjectId).TeamId;
            Team team = db.Teams.Find(teamId);

            UserTeam userTeam = db.UserTeams.Where(x => x.UserId == userId && x.TeamId == teamId).FirstOrDefault();
            if (userTeam != null)
            {
                if (team.OrganizerId == userId && User.IsInRole("Organizer"))
                {
                    isOrganizer = true;
                }
                else
                {
                    if (User.IsInRole("Member"))
                        isMember = true;
                }

            }
        }
    }
}

ActivityManager/Controllers/TaskController.cs
using ActivityManager.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ActivityManager.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpGet]
        public ActionResult GetAll()
        {
            var tasks = db.Tasks;
            ViewBag.Tasks = tasks;
            return View();
        }

        public ActionResult Show(int id)
        {
            bool isMember = false;
            bool isOrganizer = false;

            Task task = db.Tasks.Include(i => i.TaskStatus).Include(i => i.CreatedBy).Include(i => i.AssignedTo)
                .SingleOrDefault(x => x.Id == id);
            
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if ( isMember || isOrganizer || User.IsInRole("Administrator"))
            {
                if (TempData.ContainsKey("message"))
                {
                    ViewBag.message = TempData["message"].ToString();
                }
                task.Comments = db.Comments.Where(x => x.TaskId == id).Include(x => x.User);
                ViewBag.Task = task;
                ViewBag.afisareButoane = false;
                if (isOrganizer || User.IsInRole("Administrator"))
                {
                    ViewBag.afisareButoane = true;
                }
                ViewBag.esteAdmin = User.IsInRole("Administrator");
                ViewBag.utilizatorCurent = User.Identity.GetUserId();
                return View(task);
            }
            else
            {
                TempData["message"] = "You don't have the right to see this task!";
                return Redirect("~");
            }
        }

        public ActionResult New(int? projectId)
        {
            if (projectId != null)
            {
                Task task = new Task
                {
                    Projects = GetAllProjects() //vor trebui aduse doar proiectele echipei din care este membru
                };

                bool isMember = false;
                bool isOrganizer = false;
                GetRoleInTeam(ref isMember, ref isOrganizer, projectId ?? 0);

                if (isOrganizer || User.IsInRole("Administrator"))
                {
                        task.ProjectId = projectId.Value;
                        return View(task);
                }
                else
                {
                        TempData["message"] = "You don't have the right to create a new task!";
                        return Redirect("~");
                }
            }
            TempData["message"] = "You need to select a project first!";
            return Redirect("~");
        }

        [HttpPost]
        public ActionResult New(Task task)
        {
            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if (isOrganizer || User.IsInRole("Administrator"))
            {
                task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                try
                {
                    if (ModelState.IsValid)
                    {
                        task.CreatedOn = DateTime.Now;
                        task.StartDate = null;
                        task.EndDate = null;
                        task.TaskStatusId = 1;
                        task.CreatedById = User.Identity.GetUserId();
                        task.AssignedToId = null;
                        //task.TaskStatuses = GetAllTaskStatuses();
                        db.Tasks.Add(task);
                        db.SaveChanges();
                        TempData["message"] = "The task has been created!";
                        return RedirectToAction("Show", "Project", new { id = task.ProjectId });
                    }
                    else
                    {
                        return View(task);
                    }
                }
                catch (Exception e)
                {
                    System.Console.WriteLine(e);
                    return View(task);
                }
            }
            else
            {
                TempData["message"] = "You don't have the right to create a new task!";
                return Redirect("~");
            }
        }

        public ActionResult Edit(int id)
        {
            Task task = db.Tasks.Where(x => x.Id == id).Include(x => x.Project).FirstOrDefault();

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if (isOrganizer|| isMember || User.IsInRole("Administrator"))
            {
                task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                task.TaskStatuses = GetAllTaskStatuses();
                task.TeamPersons = GetTeamPersons(task.Project.TeamId);
                task.Comments = db.Comments.Where(x => x.TaskId == id);
                ViewBag.Task = task;
                // daca este doar membru, poate modifica doar statusul
                ViewBag.SeeAll = (isOrganizer || User.IsInRole("Administrator"));
                return View(task);
            }
            else
            {
                TempData["message"] = "You don't have the right to edit this task!";
                return Redirect("~");
            }
        }

        [HttpPut]
        public ActionResult Edit(int id, Task requestTask)
        {
            Task task = db.Tasks.Where(x => x.Id == id).Include(x => x.Project).FirstOrDefault();
            requestTask.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
            requestTask.TaskStatuses = GetAllTaskStatuses();
            requestTask.TeamPersons = GetTeamPersons(task.Project.TeamId);

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);
            ViewBag.SeeAll = (isOrganizer || User.IsInRole("Administrator"));

            try
            {
                if (ModelState.IsValid)
                {
                    task.Projects = GetAllProjects(); //vor trebui aduse doar proiectele echipei din care este membru
                    task.TaskStatuses = GetAllTaskStatuses();
                    task.TeamPersons = GetTeamPersons(task.Project.TeamId);
                    if (requestTask.StartDate > requestTask.EndDate)
                    {
                        TempData["error"] = "The start date cannot be set after the end date.";
                        //                        ViewBag.message = TempData["error"].ToString();
                        return View(requestTask);
                    }
                    //if ((requestTask.TaskStatusId == 1 && (requestTask.StartDate != null || requestTask.EndDate != null))
                    //    || (requestTask.TaskStatusId == 2 && (requestTask.StartDate == null || requestTask.EndDate != null))
                    //    || (requestTask.TaskStatusId == 3 && (requestTask.StartDate == null || requestTask.EndDate == null)))
                    //{
                    //    TempData["message"] = "Datele introduse nu sunt corecte!";
                    //    return View(requestTask);
                    //}
                    task.Comments = db.Comments.Where(x => x.TaskId == id);
                    if (TryUpdateModel(task))
                    {
                        task.Title = requestTask.Title;
                        task.Description = requestTask.Description;
                        task.StartDate = requestTask.StartDate;
                        task.EndDate = requestTask.EndDate;
                        task.TaskStatusId = requestTask.TaskStatusId;
                        task.AssignedToId = requestTask.AssignedToId;
                        db.SaveChanges();
                        TempData["message"] = "The task has been edited!";
                    }
                    return RedirectToAction("Show", new { id = task.Id });
                }
                else
                {
                    return View(requestTask);
                }

            }
            catch (Exception e)
            {
                return View(requestTask);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            Task task = db.Tasks.Find(id);

            bool isMember = false;
            bool isOrganizer = false;
            GetRoleInTeam(ref isMember, ref isOrganizer, task.ProjectId);

            if ((task.CreatedById == User.Identity.GetUserId() && isOrganizer )|| User.IsInRole("Administrator"))
            {
                db.Tasks.Remove(task);
                db.SaveChanges();
                TempData["message"] = "The task was deleted!";
                return RedirectToAction("Show", "Project", new { id = task.ProjectId });
            }
            else
            {
                TempData["message"] = "You don't have the right to delete this task!";
                return Redirect("~");
            }
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllProjects()
        {
            var selectList = new List<SelectListItem>();
            string userId = User.Identity.GetUserId();
            var teamsIds = db.UserTeams.Where(x => x.UserId == userId).Select(x => x.TeamId);
            var projects = db.Projects.Where(x => teamsIds.Contains(x.TeamId));
            foreach (var project in projects)
            {
                selectList.Add(new SelectListItem
                {
                    Value = project.Id.ToString(),
                    Text = project.Name
                });

ActivityManager/Views/Task/Edit.cshtml
@model ActivityManager.Models.Task

@{
    ViewBag.Titlu = "Edit task";
}

<h2>@ViewBag.Titlu </h2>

@if (TempData.ContainsKey("error"))
{
    <br />
    <div class="alert alert-danger" role="alert">
        <h4>@TempData["error"]</h4>
    </div>
}

<div class="panel panel-default">
    <form method="post" action="/Task/Edit/@Model.Id">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HttpMethodOverride(HttpVerbs.Put)
        @Html.HiddenFor(m => m.Id)
        <div class="panel-body">
            @Html.Hidden("ProjectId", Model.ProjectId, new { @class = "form-control" })
            @if (ViewBag.SeeAll)
            {
                @Html.Label("Title", "Title")
                <br />
                @Html.TextBox("Title", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, null, new { @class = "text-danger " })
                <br />
                @Html.Label("Description", "Description")
                <br />
                @Html.TextArea("Description", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger " })
                <br />
            }
            else
            {
                @Html.HiddenFor(m => m.Title);
                @Html.HiddenFor(m => m.Description);
                @Html.HiddenFor(m => m.AssignedToId);
                @Html.HiddenFor(m => m.StartDate);
                @Html.HiddenFor(m => m.EndDate);
            }
            <label>Select status</label>
            @Html.DropDownListFor(m => m.TaskStatusId, new SelectList(Model.TaskStatuses, "Value", "Text"), "Select status", new { @class = "form-control" })
            <br />

            @if (TempData.ContainsKey("message"))
            {
                <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
                <br />
            }
            @if (ViewBag.SeeAll)
            {
                <label>Assigned to </label>
                @Html.DropDownListFor(m => m.AssignedToId, new SelectList(Model.TeamPersons, "Value", "Text"), "Select person", new { @class = "form-control" })
                <br />
                <label>Start date</label>
                <br />
                @Html.TextBoxFor(m => m.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                <br />
                <label>End date</label>
                <br />
                @Html.TextBoxFor(m => m.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            }
        </div>

        <div class="panel-footer">
            <button class="btn btn-sm btn-success" type="submit"> Save </button>
            <a class="btn btn-sm btn-danger" href="/Task/Show/@Model.Id"> Cancel </a>
        </div>
    </form>
</div>

ActivityManager/Views/Task/GetAll.cshtml
@{
    ViewBag.Title = "GetAll";
}

<h2>TaskGetAll</h2>


@foreach (var stire in ViewBag.Tasks)
{
    <p>Titlu: @stire.Title</p>
    <p>Descriere: @stire.Description</p>
    <br /><br /><br />
}

ActivityManager/Views/Task/New.cshtml
@model ActivityManager.Models.Task

@{
    ViewBag.Titlu = "New task";
}

<h2>@ViewBag.Titlu</h2>

<div class="panel panel-default">
    <form method="post" action="/Task/New">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="panel-body">
            @Html.Label("Title", "Title")
            <br />
            @Html.TextBox("Title", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title, null, new { @class = "text-danger " })
            <br />
            @Html.Label("Description", "Description")
            <br />
            @Html.TextArea("Description", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger " })
            <br />
            @Html.Hidden("ProjectId", Model.ProjectId, new { @class = "form-control" })
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-sm btn-success"> Add </button>
            @if (@Model.ProjectId != 0)
            {
                <a class="btn btn-sm btn-danger" href="/Project/Show/@Model.ProjectId">Cancel</a>
            }
        </div>
    </form>
</div>

ActivityManager/Views/Task/Show.cshtml
@model ActivityManager.Models.Task

@{
    ViewBag.Title = "Task " + @Model.Title;
}

@if (ViewBag.message != null)
{
    <br />
    <div class="alert alert-success" role="alert">
        <h4>@ViewBag.message</h4>
    </div>
}

<h2>@ViewBag.Title</h2>

<div class="panel panel-default">
    <div class="panel-heading">

        <form method="post" action="/Task/Delete/@Model.Id">
            <a class="btn btn-sm btn-success" href="/Task/Edit/@Model.Id">Edit</a>
            <a class="btn btn-sm btn-success" href="/Project/Show/@Model.ProjectId">Back to project</a>

            @if (ViewBag.afisareButoane == true && Model.CreatedById == ViewBag.utilizatorCurent || ViewBag.esteAdmin)
            {

                @Html.HttpMethodOverride(HttpVerbs.Delete)
                <button class="btn btn-sm btn-danger" type="submit">Delete task</button>

            }
        </form>
    </div>
    <div class="panel-body">
        <strong> Description: </strong> @Model.Description
        <br />
        <strong> Status: </strong> @Model.TaskStatus.Status
        <br />
        @if (@Model.AssignedToId != null)
        {
            <label> Assigned to: </label> @Model.AssignedTo.Email
            <br />
        }
        @if (@Model.StartDate != null)
        {
            <label> Start date: </label> @Model.StartDate
            <br />
        }
        @if (@Model.EndDate != null)
        {
            <label> End date: </label> @Model.EndDate
            <br />
        }
        <strong> Created on: </strong> @Model.CreatedOn
        <br />
        <strong> Created by: </strong> @Model.CreatedBy.Email
        <br />
    </div>
    <div class="panel-footer">
        <h3>
            Comentarii
            <a href="@Url.Action("New", "Comment", new { taskId = @Model.Id })" class="btn btn-sm btn-success" role="button" style="float: right;"> Add new comment</a>
        </h3>
        @foreach (var comment in Model.Comments)
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    @comment.User.Email
                    <span style="float: right;"> @comment.CreatedOn </span>
                </div>
                <div class="panel-body">
                    <p>@comment.Content </p>
                </div>
                @if (@comment.User.Id == @ViewBag.utilizatorCurent)
                {
                    <div class="panel-footer">
                        <form method="post" action="/Comment/Delete/@comment.Id">
                            <a class="btn btn-sm btn-success" href="/Comment/Edit/@comment.Id"> Edit </a>
                            @Html.HttpMethodOverride(HttpVerbs.Delete)
                            <button class="btn btn-sm btn-danger" type="submit"> Delete </button>
                        </form>
                    </div>
                }
            </div>
            <br /><br />
        }

    </div>
</div>
<br />